In [3]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [8]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [29]:
np.random.rand(5, 5)

array([[0.49221994, 0.04939405, 0.87317837, 0.82490481, 0.91706724],
       [0.4857665 , 0.82374216, 0.01383607, 0.39763183, 0.60996055],
       [0.9357585 , 0.53920038, 0.94914795, 0.88571982, 0.14862264],
       [0.44616522, 0.07709534, 0.47433722, 0.14222166, 0.49277785],
       [0.08580923, 0.14301958, 0.03408686, 0.44206154, 0.4415096 ]])

In [31]:
np.random.randn(4, 4)

array([[-0.44133446, -0.23667213,  1.31299791, -1.52497179],
       [-0.74883466,  0.60648898,  1.42923884,  1.0255013 ],
       [-0.52594748, -1.24376885,  0.46213461, -0.69964676],
       [ 0.02549701,  0.65700049, -0.14402007, -0.76001584]])

In [34]:
np.random.randint(1, 100, 10)

array([22, 50, 43, 99, 23, 72, 92, 23, 55,  4])

In [38]:
arr  = np.arange(25)

In [39]:
ranrr = np.random.randint(0, 50, 10)

In [40]:
ranrr

array([23,  5, 19, 10, 24, 38, 41, 29, 26, 27])

In [41]:
ranrr.max() 

41

In [42]:
ranrr.min()

5

In [43]:
ranrr.argmax()

6

In [44]:
ranrr.argmin()

1

In [46]:
arr.shape

(25,)

In [47]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
arr.dtype

dtype('int64')